### ISSUE TITLE
yarn: `Unrecognized or legacy configuration settings found` when installing dependencies

### ISSUE THREAD

**Issue by dividedmind** [getappmap/vscode-appland#600] opened 2023-01-18 23:58 UTC
```
Error: Failed to install dependencies
Exit code: 1
Signal: null
Stdout: [31m[1mUsage Error[22m[39m: Unrecognized or legacy configuration settings found: path - run "yarn config -v" to see the list of settings supported in Yarn (in <environment>)

[1m$ [22myarn up [-i,--interactive] [-E,--exact] [-T,--tilde] [-C,--caret] [-R,--recursive] [--mode #0] ...

    at ChildProcess.<anonymous> (\src\services\nodeProcessService.ts:236:20)
    at Object.onceWrapper (node:events:646:26)
    at ChildProcess.emit (node:events:538:35)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
```

**Comment by lachrist** [comment] 2023-01-23 09:19
duplicate of https://github.com/getappmap/vscode-appland/issues/557

**Closed by lachrist** 2023-01-23 09:19 UTC
