### ISSUE TITLE
Runtime Analysis Formatting breaks when secret finding is multi-line

### ISSUE THREAD

**Issue by petecheslock** [getappmap/vscode-appland#478] opened 2022-10-13 20:40 UTC
VS Code extension `0.46.0`
[Using the sample ruby on rails project](https://github.com/land-of-apps/sample_app_6th_ed/) the codespaces-devcontainer branch. 

When running tests `bundle exec rake test` there is a multi-line finding for secret in logs and it breaks the display on the left column view. 

<img width="783" alt="Screen Shot 2022-10-13 at 4 38 29 PM" src="https://user-images.githubusercontent.com/511733/195705991-94e3f969-ed9e-4c68-b7ff-6c4495debf79.png">
 
<img width="1389" alt="Screen Shot 2022-10-13 at 9 28 16 AM" src="https://user-images.githubusercontent.com/511733/195706010-15fecc45-2108-4719-87e7-fdccc4187d30.png">

**Comment by ahtrotta** [comment] 2022-10-13 20:44
I think this is a duplicate of getappmap/board#187

**Closed** 2022-10-21 12:08 UTC
Labels: bug
